### ISSUE TITLE
Failed test suite, fresh clone

### ISSUE THREAD

**Issue by Guppster** [faustbrian/Ark-Ruby#1]
Cloning this repository, running `bin/setup`, and then running `rake spec` resulted in: `47 examples, 35 failures, 12 pending`

The majority of these failures are caused by:  
```
Faraday::ConnectionFailed:
        Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
```
Is the readme missing a setup step?

**Comment by faustbrian** [comment]
If you would take a quick look at the test files you will see that there are `env` variables you will need to specify.

**Comment by Guppster** [comment]
Oops! Didn't see that .env.example file. 
I wrote a bit about it in the readme so its more visible

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Ark-Ruby/pull/2
